"use client";

import { useEffect, useState } from "react";
import { render } from "@react-email/components";
import { Render, Data } from "@puckeditor/core";

import { useLocalStorageJson } from "@/hooks/use-local-storage-json";
import LoadingIndicator from "@/components/loading-indicator";
import FloatingButton from "@/components/floating-button";
import { emptyData } from "@/lib/puck-data/empty-data";

import conf from "@/registry/react-email/puck/configs";

export default function Renderer() {
  const [data] = useLocalStorageJson<Data>("react-email-puck-data", emptyData);
  const [page, setPage] = useState("");

  // Render the email page when the component mounts or data loads
  useEffect(() => {
    if (!data) return;

    const renderPage = async () => {
      const rendered = await render(<Render config={conf} data={data} />);

      setPage(rendered);
    };

    renderPage();
  }, [data]);

  if (!data || !page) {
    return <LoadingIndicator />;
  }

  // Safe to use dangerouslySetInnerHTML because the content is generated by React Email
  // from local storage data
  return (
    <>
      <div dangerouslySetInnerHTML={{ __html: page }} />
      <FloatingButton href="/demo/react-email/edit">Edit Email</FloatingButton>
    </>
  );
}
